### ISSUE TITLE
ModuleNotFoundError: No module named 'plot_tsne'

### ISSUE THREAD

**Issue by oceanzhf** [xsc1234/Invisible-Relevance-Bias#2]
Dear Author,

Your work has been inspirational to me, and I would like to build upon it with some innovations. However, when I ran the comparison_flava_5.py file, it raised an error: ModuleNotFoundError: No module named 'plot_tsne'. I noticed that the plot_tsne file seems to be missing from the project.

**Comment by xsc1234** [comment]
You can directly comment out the plot_tsne related code, this is just an auxiliary analysis.
